### ISSUE TITLE
Need a way to refresh aos-pyez to obtain new blueprint information

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#14]
Creating and deleting a blueprint in AOS UI, then trying to refer to the BP Again within an AOS Session module seems to break when using the same name twice.  Understandably this is probably because the bpID doesn't exist anymore, and the API doesn't ask AOS for the blueprint information a second time?

How do we refresh the AOS-PyEZ module ?

```

>>> from apstra.aosom.session import Session
>>> aos = Session('192.168.59.250')
>>> aos.login()
>>> bp = aos.Blueprints['Virtual']
>>> bp.exists
True
>>> print bp.params.names
[u'external_router_interfaces', u'leaf_loopback_ips', u'spine_leaf_link_ips', u'mlag_domain_svi_subnets', u'to_external_router_link_ips', u'leaf_asns', u'hcls', u'node_mlag_virt_1_leaf1_interfaces', u'devices', u'node_spine1_interfaces', u'spine_loopback_ips', u'deploy', u'spine_asns', u'logical_device_maps', u'resource_pools', u'node_spine2_interfaces', u'node_mlag_virt_2_leaf1_interfaces', u'node_mlag_virt_1_leaf2_interfaces', u'hostnames', u'external_links', u'node_mlag_virt_2_leaf2_interfaces', u'node_lag_virt_leaf_interfaces', u'port_maps']
>>> 

```
In AOS - delete blueprint, or change it - do something outside of AOS-PyEZ, and AOS-PyEZ doesn't know what's going on anymore.
[need to refresh?]
For example, just deleting the blueprint - AOS-PyEZ thinks it's still available.
```
>>> bp.exists
True
>>> bp.params
<apstra.aosom.amods.blueprints.BlueprintItemParamsCollection object at 0x7efcba258f50>
>>> bp.params.names
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/apstra/aosom/amods/blueprints.py", line 115, in names
  File "build/bdist.linux-x86_64/egg/apstra/aosom/amods/blueprints.py", line 122, in digest
apstra.aosom.exc.SessionRqstError: error fetching slots

>>> 

```
The blueprint doesn't exist anymore.

**Comment by jpsenior** [comment]
To refresh cache: --> bp.digest()

aos.<collection>.digest()
aos.Blueprints['Virtual'].digest()

**Comment by jeremyschulman** [comment]
please try:
````python
aos.Blueprints.digest()
````

The digest() is a method on the Collections objects.

**Comment by jeremyschulman** [comment]
also, if you want to re-read a given item, then you would do:

````python
any_item.read()
````
