### ISSUE TITLE
RFE: aos.CollectionItem 

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#23]
It would be helpful to delete a CollectionItem directly in addition to deleting it through .value

>>> del aos.AsnPools['Private']
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: 'AsnPools' object does not support item deletion

>>> del aos.AsnPools['Private'].value

**Comment by jpsenior** [comment]
One of the other use cases I have in mind is to return 'True' if the value was deleted successfully or not.  

Exception handling on attribute deletion is difficult

**Comment by jeremyschulman** [comment]
@jpsenior - aos-pyez also provided a item.delete() method.  I would prefer this use rather than overloading the python `del` operator.  The latter approach would rob the programmer from the underlying python capability to delete an object.
