### ISSUE TITLE
Question: Dynamic module 'dir' functionality

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#24]
In order for a Module in the ModuleCatalog to show up, it has to be 'used' at least once.

Is it possible to set things up so that when I browse AOS with 'dir' I can see all of the submodules?

Candidate for Documentation

```
>>> for module in aos.ModuleCatalog: getattr(aos, module)
<bunch of output>

>>> dir(aos)
['Api', 'AsnPools', 'Blueprints', 'DEFAULTS', 'DYNMODULEDIR', 'DesignTemplates', 'Devices', 'ENV', 'ExternalRouters', 'IpPools', 'LogicalDeviceMaps', 'LogicalDevices', 'ModuleCatalog', 'RackTypes', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__metaclass__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_aos_dynamic_catalog_', '_aos_dynamic_module_', '_probe', '_set_login', 'api', 'login', 'passwd', 'port', 'server', 'user']
```

**Comment by jeremyschulman** [comment]
@jpsenior - I'm not clear why simply looking at ModuleCatalog is too inconvenient for the Programmer.  At present, the architectural design approach for dir() was to show only that which is in use.  Could you please explain why the existing functionality is not sufficient?

**Comment by jpsenior** [comment]
@jeremyschulman how do we expose more information about the available API endpoints (modules) at runtime/development time?  

Use cases are eg dir() functionality in [i]python or within an IDE.  ModuleCatalog in particular is a static method that we could expose additional module items to, allowing code-completion within Pycharm for instance.

I would like to see me typing aos.Blueprints[tab] and see that aos.Blueprints.create() is an available method, and these are the available functions (params, names create, delete, etc).

I'm coming from the perspective of a blind user with an API.  We use functions like help(), dir(), etc to navigate libraries.

**Comment by jeremyschulman** [comment]
@jpsenior - I understand your use-case for IDE tab-completion.  For the other use-case, the Programmer can always check <owner>.ModuleCatalog for available items.   

The over-arching goal with the on-demand loading of modules was to use only that which is required; and keep those modules constrained by the AOS version number.  So I'd have to give this some more thought in terms of how to achieve what you want for the IDE use case.

**Comment by jeremyschulman** [comment]
closing this issue after further thoughts on this.  the ask is to enhance an IDE experience uniquely.
