### ISSUE TITLE
RFE: aos.CollectionItem.create() optional synchronization

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#25]
Currently the function returns None if it creates a resource properly, and returns immediately.

Can we have a blocking argument to aos.CollectionItem.create(wait=True, timeout=10) or similar that can wait for 3, 4 seconds and GET the resource it just tried to create, waiting for HTTP 200?

The desired behavior would be when HTTP 200 OK comes back, return True, or return the collection value with the newly mapped item ID.

When building a complex blueprint and posting many resources, AOS internally spends a few seconds scaffolding resources.

A  user of PyEZ may want PyEZ to wait for this delay instead of adding retry-type boilerplate code.

Current behavior:

>>> aos.AsnPools['new_asn'].create(data)
None

<object is immediately created, but doesn't yet exist on AOS>
If we try to assign the new ASN pool to a blueprint slot immediately (next line of code) we get a SessionError.

This is particularly important for blueprints, if we want to assign resource slots we have to wait for the resources to exist before trying to use them right away.

**Comment by jeremyschulman** [comment]
@jpsenior - are you actually seeing this specific error behavior?  From my experience, creating an a new ASN pool for example, the result of the create (POST) does result in a new ID being returned, and it can be used immediately.

The only exception to this use-pattern is the creation of a blueprint item.  And in that specific case, there is a mechanism within the item to wait for the blueprint to exist (i.e. block).

**Comment by jpsenior** [comment]
@jeremyschulman I need to dig through some code, but it seems I had problems with delete() taking a few more seconds longer than expected (from a pure AOS DELETE /resource-pools/ perspective), but create() should be fine.

The use case was DELETE and immediately POST/PUT/PATCH the same resource back.  Without HTTP GET the resource back and waiting for a non-400 response, we could POST an ID that wasn't actually ready yet.  

The code example I have in mind was related to external-routers

In any case, let's close this request for now until I run into a new problem. I posted internal AOS RFEs/Bugs that resolved the root cause issue.
