### ISSUE TITLE
RFE: CollectionItem.Find() enhancement - optional method

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#26]
It would be helpful to use aos.AsnPools.find() without any parameters, defaulting 'key' to arg1 and method to both display_name and id.

This will help with parsing json/yml files on-disk in storage: eg storing a template with a logical device 'name' instead of 'ID', but still allowing us to use the ID if we copy-paste a running blueprint.

Current usage:
```
>>> aos.AsnPools.find(key="97f6113d-757a-4dbe-8af7-bf775c24350a", method="id", )
{u'status': u'in_use', u'display_name': u'Private', u'tags': [], u'created_at': u'2016-12-19T18:20:39.870530Z', u'last_modified_at': u'2016-12-19T18:20:39.870530Z', u'ranges': [{u'status': u'pool_element_in_use', u'last': 65535, u'first': 65412}], u'id': u'97f6113d-757a-4dbe-8af7-bf775c24350a'}
```
Wish-list usage
```
>>> aos.AsnPools.find("Private")
{u'status': u'in_use', u'display_name': u'Private', u'tags': [], u'created_at': u'2016-12-19T18:20:39.870530Z', u'last_modified_at': u'2016-12-19T18:20:39.870530Z', u'ranges': [{u'status': u'pool_element_in_use', u'last': 65535, u'first': 65412}], u'id': u'97f6113d-757a-4dbe-8af7-bf775c24350a'}

>>> aos.AsnPools.find("97f6113d-757a-4dbe-8af7-bf775c24350a")
{u'status': u'in_use', u'display_name': u'Private', u'tags': [], u'created_at': u'2016-12-19T18:20:39.870530Z', u'last_modified_at': u'2016-12-19T18:20:39.870530Z', u'ranges': [{u'status': u'pool_element_in_use', u'last': 65535, u'first': 65412}], u'id': u'97f6113d-757a-4dbe-8af7-bf775c24350a'}
```

**Comment by jeremyschulman** [comment]
@jpsenior - it's not clear to me what you are asking for beyond what actually exists, wrt.

>>> aos.AsnPools.find("Private")

This is the same as:

>> item = aos.AsnPools['Private']
>> item.exists       # will show True or False

The second example:
>>> aos.AsnPools.find("97f6113d-757a-4dbe-8af7-bf775c24350a")

the parameter is arbitrary to the aos-pyez; i.e. it would not know how to interpret this value; is it an ID string or a name string?

I do not understand how this feature request would make it helpful for parsing json/yaml files.  Could you please explain in more detail?

**Comment by jeremyschulman** [comment]
after follow-up with @jpsenior, closing this issue as the existing library provides the desired functionality.
