### ISSUE TITLE
RFE: CollectionItem.create() exception for Duplicate items

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#27]
CollectionItem.create() either creates the item and returns NoneType, or throws a Session exception. Can we have a seperate exception for duplicated items?  A session error will imply a username/password issue or HTTP Timeout, but if the real issue is a duplicate item this is program  around without parsing the exception message text.

**Comment by jeremyschulman** [comment]
@jpsenior - there is issue #22 that I can use to track; so closing this one as duplicate.
