### ISSUE TITLE
collectionItem create() does not return a value

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#28]
CollectionItem.create() does not return any value (NoneType).

Can we please have this function return got.content?
Docstring says "Returns: the result of the :meth:`write` call.
Actually it returns nothing.  I can't tell if the resource  is created or not.

logical_devices = list_of_dicts_for_logical_devices

EG usage:
The code below never prints 'Added Logical Device', because 'result' is always None.

```
for logical_device in logical_devices:
    try:
        result = aos.LogicalDevices[logical_device['display_name']].create(logical_device)
        if result:
            print "Added Logical Device", logical_device['display_name'], result
    except SessionError as e:
        print 'Failed to add Logical device', logical_device['display_name'], e
```

**Comment by jeremyschulman** [comment]
the .create() method will now return the `self` instance.  Meaning that you can do:

new_item = collection['name'].create(data)

if you want the actual JSON data you can then access it via `new_item.value`
