### ISSUE TITLE
RFE: CollectionItem delete() method

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#30]
The only way to delete an item right now is to use the 'del' function.

In 'develop' branch right now, from collection_item.py:
```
   @value.deleter
    def value(self):
```

@jeremyschulman we discussed this briefly on slack, just tracking this here. I didn't see a delete() in the develop or improvements branches.

Usage case:

if aos.AsnPools['Private'].delete():
  print 'Delete successful!'

The only way I can delete a value right now does not allow me to do exception handling or get a callback if the deletion was successful or not.

`del aos.AsnPools['Private'].value`

**Comment by jeremyschulman** [comment]
@jpsenior - it's under developed; but it does exist.  Closing this issue.
