### ISSUE TITLE
RFE: debug logging

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#31]
It would be helpful from an AOS/Development perspective to debug HTTP GET/POST/DEL URLs, body, and content as an optional feature with multiple verbosity levels.

Today I use a number of custom methods to do various AOS integration tests / Bug regression testing, it would be helpful to move my code to aos-pyez with this feature.

Verbosity '1' would be to print (with logging module for stdout) the Timestamp, METHOD, URL
Verbosity '2' would add the post body, with pprinted output if JSON

Desired output:
DELETE http://192.168.59.250:8888/api/design/templates/2ccdbc97-3d47-4197-b266-04d551b3c059 
{
}

GET http://192.168.59.250:8888/api/design/templates
{
<pretty-printed json content of HTTP response>
}

**Comment by jeremyschulman** [comment]
@jpsenior - I understand the request, and appreciate the functionality it would provide.  I would propose that we investigate what (if any) debug/logging capabilities exist within the `requests` library natively.  The alternative to "wrap" every requests call with a method to provide debug/logging would be a fairly intrusive change to the code base.  So for now, I'm going to mark this issue an under investigation and assign to you.  If you don't have the bandwidth to investigate, please let me know and I'll reassign.  Thank you.

**Comment by jeremyschulman** [comment]
@jpsenior - I am going to close this issue if you have not done any investigation per 30/dec comment.

**Comment by jeremyschulman** [comment]
It appears there is a way to hook natively into the request library as I suspected.  I haven't dug into all of this, but starting here:

http://docs.python-requests.org/en/master/api/

**Comment by jeremyschulman** [comment]
Examples on how to do this are here:
[examples](http://stackoverflow.com/questions/16337511/log-all-requests-from-the-python-requests-module)

Closing this issue.
