### ISSUE TITLE
Setting blueprint params overrides wipes previous slots (PUT vs PATCH)

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#36]
When creating multiple blueprint parameter assignments in order (eg, to force leaf_asns to get ASNs first), only the most previously assigned resource in the parameter slot is actually assigned to the blueprint.

This is due to requests.put instead of requests.patch when setting resources in a blueprint.

I am doing this in two sequential operations to ensure leaf_asns are assigned before spine_asns, however the use case is valid when using an iterating function to assign blueprint parameters as well - ex, 'not all at once'

As a user, I would expect behavior of slot assignment to work by default as a PATCH instead of the current PUT, but provide a method for overriding this (eg, replace=True) if an operator wanted to delete existing assignments.

**Current behavior:**
```
aos.Blueprints['Virtual'].params['resource_pools'].value = {'leaf_asns': [aos.AsnPools['Private'].id]}
aos.Blueprints['Virtual'].params['resource_pools'].value = {'spine_asns': [aos.AsnPools['Private'].id]}

202 PUT http://192.168.59.250:8888/api/blueprints/b664bf63-ac5a-4eaf-bf14-f9fe38b35fed/slots/resource_pools  Assigning leaf_asns - {'leaf_asns': [u'6c34f112-d018-4746-b173-196ff2869c22']}
202 PUT http://192.168.59.250:8888/api/blueprints/b664bf63-ac5a-4eaf-bf14-f9fe38b35fed/slots/resource_pools  Assigning spine_asns - {'spine_asns': [u'6c34f112-d018-4746-b173-196ff2869c22']}
```
When checking device assignments now in AOS, I can see that only spine ASNs are assigned and leaf ASNs are missing.

**Expected behavior:**
I modified slot_params.py under the BlueprintItemParamsItem.write() function to add a debug and change the method from requests.patch to requests.put.
Setting a resource pool now behaves as expected: leaf_asns is not overwritten, and AOS assigns spine and leaf at the same time.
_patch slot_params.py_
```    
def write(self, replace_value):
        got = requests.patch(self.url, headers=self.api.headers, json=replace_value)
        print got.status_code, got.request.method, got.request.url, got.content,
```
_testing_
```
aos.Blueprints['Virtual'].params['resource_pools'].value = {'leaf_asns': [aos.AsnPools['Private'].id]}
aos.Blueprints['Virtual'].params['resource_pools'].value = {'spine_asns': [aos.AsnPools['Private'].id]}

202 PATCH http://192.168.59.250:8888/api/blueprints/b664bf63-ac5a-4eaf-bf14-f9fe38b35fed/slots/resource_pools  Assigning leaf_asns - {'leaf_asns': [u'6c34f112-d018-4746-b173-196ff2869c22']}
202 PATCH http://192.168.59.250:8888/api/blueprints/b664bf63-ac5a-4eaf-bf14-f9fe38b35fed/slots/resource_pools  Assigning spine_asns - {'spine_asns': [u'6c34f112-d018-4746-b173-196ff2869c22']}
```

All 'resource_pool' assignments are in place - both leaf and spine ASNs are assigned in the blueprint.
I have tested with a larger number of slots for blueprint assignments - everything worked fine (and as expected) with PATCH instead of PUT - dhcp server IPs, loopback IPs, slot overrides, etc.

**Comment by jeremyschulman** [comment]
@jpsenior - the writing to the `value` is expected to be a replace operation; thus the use of PUT.  

I would propose we add a new .update() method to perform the PATCH action.  Otherwise, you could simple do a read/modify/write using the existing, like the following:

````
# this does a PUT
aos.Blueprints['Virtual'].params['resource_pools'].value = {'leaf_asns': [aos.AsnPools['Private'].id]}

# do a read/modify/write(PUT)
value = aos.Blueprints['Virtual'].params['resource_pools'].value 
value.update({'spine_asns': [aos.AsnPools['Private'].id]})
aos.Blueprints['Virtual'].params['resource_pools'].value = value
````

but if we want to have a convenience of a PATCH operation, we could do

````
# this does a PUT
aos.Blueprints['Virtual'].params['resource_pools'].value = {'leaf_asns': [aos.AsnPools['Private'].id]}

# this does a PATCH
aos.Blueprints['Virtual'].params['resource_pools'].update({'spine_asns': [aos.AsnPools['Private'].id]})
````

**Comment by jpsenior** [comment]
an .update() would be great!

**Comment by jeremyschulman** [comment]
added .update() method to blueprint parameter.
