### ISSUE TITLE
Add method in_use() for all resources object

### ISSUE THREAD

**Issue by dgarros** [Apstra/aos-pyez#42]
I think it would be useful to add a method in_use() to all Collection_item object that are part of the group `resources`.   
As of today: IpPools, AsnPools and soon VlanPools

This new method will return `True` or `False` to indicate if this item is currently used or not.

These resources cannot be deleted if they are in use so this check is important.  
Later, it could be useful to add a check in delete() to return an error message directly 

Thoughts ?

**Comment by jeremyschulman** [comment]
@dgarros - at present the library provides a "bare bones" mechanism to exchanges the AOS REST API native JSON data structures.  Going forward it does make sense to start to "objectify" the library and provide a more programmer friendly set of methods/attributes that are specific to the API endpoint.  So in the case you present, it would make sense to include an "in_use" property or "in_use()" method.

So conceptually, I would agree with this suggestion and something that should be implemented in future releases of the library.

**Comment by jeremyschulman** [comment]
@dgarros - I will make this enhancement as a property for specific Resource objects that provide this property in the JSON struct.  Not sure if all CollectionItems fall into this category ... so I'll dig through it.

**Comment by jeremyschulman** [comment]
@dgarros - I've looked through the various collections, and the only two that make immediate sense is the IpPools and the AsnPools.  So I will add the property to these now.

There are a few additional candidates worth looking at, which we can discuss further.  For example, we could include Blueprints, and see if there are any associated devices (i.e. "in-use").  We can also look at Devices and use the blueprint_active or the state information to identify "in-use".  But we can discuss those separately from this issue.

**Comment by jeremyschulman** [comment]
testing:

````python
