### ISSUE TITLE
Add a variable with the version number inside the library

### ISSUE THREAD

**Issue by dgarros** [Apstra/aos-pyez#54]
it would be great to add somewhere the version number of the library inside the code itself. 

It would allow to check that is the version of pyez installed on a specific setup in case an application has a minimum requirement.

Something like that would be great:
```
from apstra.aosom import VERSION
```

**Comment by jeremyschulman** [comment]
Great suggestion, will do!

**Comment by jeremyschulman** [comment]
@dgarros, you can now do this:

````python
>>> import apstra.aosom
>>> apstra.aosom.__version__
'0.6.0'
````
