### ISSUE TITLE
Add a way to define the hcl_model of a device

### ISSUE THREAD

**Issue by dgarros** [Apstra/aos-pyez#67]
Currently, there is no easy way to define the `hcl_model` of a device. If the hcl_model is not defined it's not possible to approve the device.

It would be great to add a solution for that.

**Comment by jeremyschulman** [comment]
@dgarros - agreed, this should be a new collection with at least the primitive Collection/Item functionality.  I'll add to 0.7.0.

**Comment by jeremyschulman** [comment]
HardwareType collection added in 0.7.0 release.
