### ISSUE TITLE
Add a way to set/get the device "admin" state

### ISSUE THREAD

**Issue by dgarros** [Apstra/aos-pyez#68]
it would be great to add some methods to check what is the current `admin_state` of a device: __normal__, __decomm__  or __maint__

And also we would need the some methods to set the admin state

```python
>> dev = aos.Devices['serial']
>> dev.admin_state
"normal"
>> dev.set_maint_mode
>> dev.admin_state
"maint"
>> dev.set_normal_mode
>> dev.admin_state
"normal"
```

**Comment by jeremyschulman** [comment]
@dgarros - currently the raw state of the device can be retrieved using the `state` property:

````python
>>> dev.state
u'OOS-QUARANTINED'
````

The state is represented as two values <major>-<minor> where major is either "In Service" (IS) or "Out of Service" (OOS).  So what you see above is "Out of Service, Quarantined".  The UI presents user-friendly representations, as you describe.  We could add this mapping to the aos-pyez library if you believe that is needed.  Please advise.

**Comment by jeremyschulman** [comment]
adding to 0.7.0

**Comment by jeremyschulman** [comment]
closing
