### ISSUE TITLE
Invalid assertion error message for collection.Collection.find module

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aos-pyez#85]
under Collection.find():

        if not any([label, uid]):
            raise AccessValueError('Either `label` or `id` must be provide')

Error message should state `uid`, not `id`. Also small typo - 'must be provided'

**Comment by jeremyschulman** [comment]
minor bug; not functionally affecting.  anyone welcome to make the minor change and PR.  thank you.

**Comment by jeremyschulman** [comment]
closing due to non-interest.
